version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ~/apps/postgres-17:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8081:8081"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '4318:4318'
      - '16686:16686'

  # tracing-server:
  #   image: grafana/otel-lgtm:latest
  #   ports:
  #     - '3000:3000'
  #     - '4317:4317'
  #     - '4318:4318'

  taskforce-connector:
    build: https://github.com/taskforcesh/taskforce-connector.git#master
    environment:
      TASKFORCE_CONNECTION: ${TASKFORCE_CONNECTION:-"local taskforce provisioner"}
      TASKFORCE_TEAM: ${TASKFORCE_TEAM:-Radix}
      TASKFORCE_TOKEN: ${TASKFORCE_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # workers:
  #   hostname: workers
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/workers.Dockerfile
  #   image: workers:latest
  #   restart: always
  #   ports:
  #     - '3003:3003'
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@postgres:5432/radix-incentives
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=password
  #     - OTLP_BASE_URL=http://jaeger:4318

  # streamer:
  #   hostname: streamer
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/streamer.Dockerfile
  #   image: streamer:latest
  #   restart: always
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@postgres:5432/radix-incentives
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=password
  #     - OTLP_BASE_URL=http://jaeger:4318
  #     - WORKERS_API_BASE_URL=http://workers:3003

  # incentives:
  #   hostname: workers
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/incentives.Dockerfile
  #   image: incentives:latest
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@postgres:5432/radix-incentives
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=password
  #     - NEXT_PUBLIC_PREVIEW_BLOCK_ENABLED=2025-07-14T00:00:00.000Z