packages:
  - "packages/**"
  - "apps/**"
  - "experiments/**"
  - "tools/**"

catalog:
  tsx: "^4.19.3"
  "drizzle-orm": "^0.33.0"
  "@trpc/server": "^11.0.0"
  "@trpc/client": "^11.0.0"
  "@trpc/react-query": "^11.0.0"
  zod: "^3.23.3"
  "next-auth": "5.0.0-beta.25"
  "superjson": "^2.2.1"
  "radix-connect": "^0.2.0"
  "@radixdlt/rola": "^2.1.0"
  "jose": "^6.0.10"
  "ioredis": "^5.6.0"
  "pino": "^9.6.0"
  "@radixdlt/babylon-gateway-api-sdk": "^1.10.1"
  "@radixdlt/babylon-core-api-sdk": "^1.3.0"
  "effect": "^3.14.1"
  "radix-web3.js": "^0.3.3"
  "@aws-sdk/client-sqs": "^3.515.0"
  "@calamari-radix/gateway-ez-mode": "^1.4.0"
  "@types/aws-lambda": "8.10.147"
  "express": "^4.21.2"
  "tsup": "^8.4.0"
  "vitest": "^3.0.9"
  "@radixdlt/radix-engine-toolkit": "^1.0.5"
  "postgres": "^3.4.4"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "server-only": "^0.0.1"
  "clsx": "^2.1.1"
  "next": "^15.2.3"
  "tailwind-merge": "^3.2.0"
  "@t3-oss/env-nextjs": "^0.12.0"
  "@tanstack/react-query": "^5.69.0"
  "@radixdlt/radix-dapp-toolkit": "^2.2.1"
  "radix-transaction-stream": "^0.2.2"
  "@noble/hashes": "^1.8.0"
  "@oslojs/crypto": "^1.0.1"
  "@oslojs/encoding": "^1.1.0"
  "blakejs": "^1.2.1"
  "pino-pretty": "^13.0.0"
  "bignumber.js": "^9.3.0"
  "bullmq": "^5.53.0"
  "neverthrow": "^8.2.0"
  "@hono/node-server": "^1.14.2"
  "@opentelemetry/exporter-metrics-otlp-proto": "^0.201.1"
  "@opentelemetry/exporter-trace-otlp-proto": "^0.201.1"
  "@opentelemetry/sdk-metrics": "^2.0.0"
  "@opentelemetry/sdk-node": "^0.201.1"
  "@opentelemetry/api": "^1.9.0"
  "@opentelemetry/exporter-trace-otlp-http": "^0.200.0"
  "@opentelemetry/resources": "^2.0.1"
  "@opentelemetry/sdk-logs": "^0.201.1"
  "@opentelemetry/sdk-trace-base": "^2.0.0"
  "@opentelemetry/sdk-trace-node": "^2.0.0"
  "@opentelemetry/semantic-conventions": "^1.34.0"
  "@bull-board/api": "^6.9.6"
  "@bull-board/hono": "^6.9.6"
  "@types/make-fetch-happen": "^10.0.4"
  "make-fetch-happen": "^14.0.3"
  "inquirer": "^8.2.6"
  "@types/inquirer": "^9.0.7"
  "@types/node": "^20.0.0"
  "@date-fns/utc": "^2.1.0"
  "hono": "^4.7.10"
  "@testcontainers/postgresql": "^11.2.1"
  "commander": "^12.0.0"
  "@effect/language-service": "^0.27.2"
  "sonner": "^2.0.3"
  "csv-writer": "^1.6.0"
  "@effect/opentelemetry": "^0.47.0"
  "date-fns-tz": "^3.2.0"
  "date-fns": "^4.1.0"
  
