packages:
  - "packages/**"
  - "apps/**"

catalog:
  tsx: "^4.19.3"
  "drizzle-orm": "^0.33.0"
  "@trpc/server": "^11.0.0-rc.446"
  "@trpc/client": "^11.0.0-rc.446"
  zod: "^3.23.3"
  "next-auth": "5.0.0-beta.25"
  "superjson": "^2.2.1"
  "radix-connect": "^0.2.0"
  "@radixdlt/rola": "^2.1.0"
  "jose": "^6.0.10"
  "ioredis": "^5.6.0"
  "pino": "^9.6.0"
  "@radixdlt/babylon-gateway-api-sdk": "^1.10.1"
  "@radixdlt/babylon-core-api-sdk": "^1.3.0"
  "effect": "^3.14.1"
  "radix-transaction-stream": "^0.2.1"
  "radix-web3.js": "^0.3.3"
  "@aws-sdk/client-sqs": "^3.515.0"
  "@calamari-radix/gateway-ez-mode": "^1.4.0"
  "@types/aws-lambda": "8.10.147"
  "express": "^4.21.2"
  "tsup": "^8.4.0"
  "vitest": "^3.0.9"
  "@radixdlt/radix-engine-toolkit": "^1.0.5"
