packages:
  - "packages/**"
  - "apps/**"
  - "experiments/**"
  - "tools/**"

catalog:
  tsx: "^4.19.3"
  "drizzle-orm": "^0.33.0"
  "@trpc/server": "^11.0.0"
  "@trpc/client": "^11.0.0"
  "@trpc/react-query": "^11.0.0"
  zod: "^3.23.3"
  "next-auth": "5.0.0-beta.25"
  "superjson": "^2.2.1"
  "radix-connect": "^0.2.0"
  "@radixdlt/rola": "^2.1.0"
  "jose": "^6.0.10"
  "ioredis": "^5.6.0"
  "pino": "^9.6.0"
  "@radixdlt/babylon-gateway-api-sdk": "^1.10.1"
  "@radixdlt/babylon-core-api-sdk": "^1.3.0"
  "effect": "^3.14.1"
  "radix-web3.js": "^0.3.3"
  "@aws-sdk/client-sqs": "^3.515.0"
  "@calamari-radix/gateway-ez-mode": "^1.4.0"
  "@types/aws-lambda": "8.10.147"
  "express": "^4.21.2"
  "tsup": "^8.4.0"
  "vitest": "^3.0.9"
  "@radixdlt/radix-engine-toolkit": "^1.0.5"
  "postgres": "^3.4.4"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "server-only": "^0.0.1"
  "clsx": "^2.1.1"
  "next": "^15.2.3"
  "tailwind-merge": "^3.2.0"
  "@t3-oss/env-nextjs": "^0.12.0"
  "@tanstack/react-query": "^5.69.0"
  "@radixdlt/radix-dapp-toolkit": "^2.2.1"
  "radix-transaction-stream": "^0.2.2"
  "@noble/hashes": "^1.8.0"
  "@oslojs/crypto": "^1.0.1"
  "@oslojs/encoding": "^1.1.0"
  "blakejs": "^1.2.1"
  "pino-pretty": "^13.0.0"
