{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .external_secret_name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: {{ .secret_key }}
      remoteRef:
        key: {{ .aws_secret_name }}
        {{- if .aws_secret_key }}
        property: {{ .aws_secret_key }}
        {{- end }}
{{- end }}