{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incentives-transaction-stream.fullname" . }}-metrics
  labels:
    {{- include "incentives-transaction-stream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    name: metrics
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "incentives-transaction-stream.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incentives-transaction-stream.fullname" . }}
  labels:
    {{- include "incentives-transaction-stream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: "{{ .Values.service.port }}"
  selector:
    {{- include "incentives-transaction-stream.selectorLabels" . | nindent 4 }}