---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incentives-dapp.fullname" . }}
  labels:
    {{- include "incentives-dapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "incentives-dapp.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incentives-dapp.fullname" . }}-metrics
  labels:
    {{- include "incentives-dapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.metrics.port }}
    name: metrics
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "incentives-dapp.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.pm2_metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "incentives-dapp.fullname" . }}-pm2-metrics
  labels:
    {{- include "incentives-dapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.pm2_metrics.port }}
    name: pm2-metrics
    targetPort: {{ .Values.pm2_metrics.port }}
  selector:
    {{- include "incentives-dapp.selectorLabels" . | nindent 4 }}
{{- end }}
